apiVersion: apps/v1
kind: Deployment
metadata:
  name: billingstatements
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billingstatements
  template:
    metadata:
      labels:
        app: billingstatements
    spec:
      containers:
      - name: billingstatements
        image: whaakman/container-demos:billingstatementsv3
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: billingstatements
  labels:
    name: billingstatements
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: billingstatements   
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: billingstatements
spec:
  ingressClassName: nginx
  rules:
    - host: cloudadventures.com
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: billingstatements
                port:
                  number: 80
            path: /billingstatement
